{"name": "test_404_error", "status": "passed", "description": "Тест обработки ошибки 404", "attachments": [{"name": "stdout", "source": "a8fb9a56-9e3c-43cb-88d8-67de8a4181d4-attachment.txt", "type": "text/plain"}], "start": 1760601981148, "stop": 1760601981736, "uuid": "0c1c2849-afad-4a6d-bbc1-e14930c30e42", "historyId": "8c5edd45f53b33f4e3adabdf11981ca0", "testCaseId": "8c5edd45f53b33f4e3adabdf11981ca0", "fullName": "tests.test_api.TestJSONPlaceholderAPI#test_404_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestJSONPlaceholderAPI"}, {"name": "host", "value": "Dimon"}, {"name": "thread", "value": "20772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}], "titlePath": ["tests", "test_api.py", "TestJSONPlaceholderAPI"]}